# Generated by Django 2.0.1 on 2018-07-28 07:45

import amo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=255)),
                ('video_id', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('favorite', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'UserVideo',
                'ordering': ('favorite', '-created'),
            },
            bases=(amo.models.SearchMixin, amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
