# Generated by Django 2.0.1 on 2018-07-28 17:12

import amo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uservideo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('video_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnails', models.URLField(blank=True, max_length=255)),
                ('publishedAt', models.DateTimeField()),
            ],
            options={
                'db_table': 'Video',
                'ordering': ('-created',),
            },
            bases=(amo.models.SearchMixin, amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
