# Generated by Django 2.0.1 on 2018-07-28 06:23

import amo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoHightlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('video_id', models.CharField(max_length=255)),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
            ],
            options={
                'db_table': 'VideoHightlight',
                'ordering': ('-created',),
            },
            bases=(amo.models.SearchMixin, amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='VideoInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('video_id', models.CharField(max_length=255)),
                ('pointed_time', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'VideoInteraction',
                'ordering': ('-created',),
            },
            bases=(amo.models.SearchMixin, amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
